### ISSUE TITLE
shell: OpenWeather extension doesn't look right

### ISSUE THREAD

**Issue by berkiyo** [monday15/lounge-gtk-theme#7]
Hi there,

I recently installed an extension called OpenWeather and it turned out to be useful. Unfortunately, there seems to be a problem with the background. Here is what I mean:

![openweather_extension](https://user-images.githubusercontent.com/38805550/51776913-13cf5a80-214f-11e9-9c5c-f92d4afc31fa.png)

Adwaita and Arc don't seem to have this issue but Lounge does. Do you know what could be the problem here? It isn't a huge issue but maybe something worth looking into.

In case you're interested, I am using GNOME 3.30 on Fedora 29.

**Comment by monday15** [comment]
Thanks for reporting the issue.
Fixed with https://github.com/monday15/lounge-gtk-theme/commit/f91b9a94648baeef22d89a5eb49cbe845d4f6834, https://github.com/monday15/lounge-gtk-theme/commit/3bea8a4fb58a35d985e3904aa2285348d3e17cc5, https://github.com/monday15/lounge-gtk-theme/commit/eea5a959bab5b5885cb6982b87205e6ee2af6cb6.
Please, reopen if you'll see any other issues with this extension.
Copr repo package will be updated approximately this Saturday with 1.12 release.
